services:
  - type: web
    name: tanya-chatgpt-pro-malaysia
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    rootDir: .
    envVars:
      - key: PORT
        value: 3000
